# Generated by Django 4.2.11 on 2025-08-08 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(db_index=True, max_length=100, verbose_name='نام کالا')),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='نماد')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت نهایی')),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت میانگین')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='بیشترین قیمت')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='کمترین قیمت')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت پایه')),
                ('volume', models.PositiveIntegerField(default=0, verbose_name='حجم معاملات')),
                ('transaction_count', models.PositiveIntegerField(default=0, verbose_name='تعداد معاملات')),
                ('price_date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('source', models.CharField(db_index=True, default='scroll_time', max_length=50, verbose_name='منبع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'داده قیمت',
                'verbose_name_plural': 'داده\u200cهای قیمت',
                'indexes': [models.Index(fields=['commodity_name', 'price_date'], name='price_model_commodi_b439f1_idx'), models.Index(fields=['symbol', 'price_date'], name='price_model_symbol_85625f_idx'), models.Index(fields=['source', 'created_at'], name='price_model_source_78fc9f_idx')],
                'unique_together': {('commodity_name', 'symbol', 'price_date', 'source')},
            },
        ),
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('total_records', models.PositiveIntegerField(default=0, verbose_name='تعداد کل رکوردها')),
                ('imported_records', models.PositiveIntegerField(default=0, verbose_name='تعداد رکوردهای وارد شده')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'لاگ واردات',
                'verbose_name_plural': 'لاگ\u200cهای واردات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='price_model_status_26218d_idx'), models.Index(fields=['commodity_name', 'start_date'], name='price_model_commodi_7cc204_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('value', models.IntegerField(verbose_name='مقدار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='price_models.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['parent', 'is_active'], name='price_model_parent__c79023_idx'), models.Index(fields=['value'], name='price_model_value_039c72_idx')],
            },
        ),
    ]
