# Generated by Django 4.2.11 on 2025-08-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='commodity_name',
            field=models.CharField(choices=[('کنسانتره آهن', 'کنسانتره آهن'), ('سنگ آهن', 'سنگ آهن'), ('کاتد مس', 'کاتد مس'), ('شمش آلومینیوم', 'شمش آلومینیوم'), ('کک متالورژی', 'کک متالورژی'), ('طلا', 'طلا'), ('نقره', 'نقره'), ('مس', 'مس'), ('آلومینیوم', 'آلومینیوم'), ('روی', 'روی')], db_index=True, max_length=100, verbose_name='نام کالا'),
        ),
    ]
