# Generated by Django 4.2.11 on 2025-08-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_populate_initial_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDataImportProxy',
            fields=[
            ],
            options={
                'verbose_name': 'وارد کردن داده قیمت',
                'verbose_name_plural': '🔄 وارد کردن داده\u200cهای قیمت',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('prices.pricedata',),
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='prices_cate_main_ca_731a26_idx',
            old_name='prices_cat_main_value_idx',
        ),
        migrations.RenameIndex(
            model_name='maincategory',
            new_name='prices_main_value_eb8fc9_idx',
            old_name='prices_main_value_idx',
        ),
        migrations.RenameIndex(
            model_name='pricedata',
            new_name='prices_pric_commodi_7594ec_idx',
            old_name='prices_pric_commodi_7c7b6b_idx',
        ),
        migrations.RenameIndex(
            model_name='pricedata',
            new_name='prices_pric_price_d_407330_idx',
            old_name='prices_pric_price_d_4a7c3f_idx',
        ),
        migrations.RenameIndex(
            model_name='scrolltimerequest',
            new_name='prices_scro_status_f86bdd_idx',
            old_name='prices_scroll_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='subcategory',
            new_name='prices_subc_categor_7a3c35_idx',
            old_name='prices_subcat_cat_value_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dataimportlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scrolltimerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
