# Generated by Django 4.2.11 on 2025-08-06 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_add_alldata_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alldata',
            new_name='prices_alld_commodi_f2738a_idx',
            old_name='prices_alldata_comm_trans_idx',
        ),
        migrations.RenameIndex(
            model_name='alldata',
            new_name='prices_alld_transac_ba9601_idx',
            old_name='prices_alldata_trans_date_idx',
        ),
        migrations.RenameIndex(
            model_name='alldata',
            new_name='prices_alld_source_af1636_idx',
            old_name='prices_alldata_source_idx',
        ),
    ]
