ARG PG_CONTAINER_VERSION=15

### مرحله ساخت (Build stage)
FROM docker.io/library/postgres:${PG_CONTAINER_VERSION}-alpine as builder

RUN apk update && apk add --no-cache \
  build-base linux-headers make postgresql-dev \
  automake libtool autoconf m4 clang llvm llvm-dev

WORKDIR /app
USER root

# ✅ نصب scws (موتور tokenize، اگه لازم باشه)
COPY ./scws-1.2.3.tar.bz2 .
RUN tar xjf scws-1.2.3.tar.bz2 \
    && cd scws-1.2.3 \
    && ./configure \
    && make install


FROM docker.io/library/postgres:${PG_CONTAINER_VERSION}-alpine
ENV LANG zh_CN.UTF-8


COPY --from=builder /usr/local/lib/libscws.* /usr/local/lib/


COPY init-db.sql /docker-entrypoint-initdb.d/
