FROM python:3.8.18-slim-bullseye

ENV GOSU_VERSION 1.16
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ARG HOST_USER_ID
ARG HOST_GROUP_ID
ARG DOCKER_GROUP_ID

RUN groupadd -g $HOST_GROUP_ID sufob \
    && useradd -r -s /bin/bash -g sufob -u $HOST_USER_ID sufob

# نصب اولیه بسته‌ها (کوچک و کم تغییر)
RUN apt-get update --yes --quiet && \
    apt-get install --yes --quiet --no-install-recommends \
    build-essential \
    libpq-dev \
    libmariadb-dev \
    libjpeg62-turbo-dev \
    zlib1g-dev \
    libwebp-dev \
    netcat \
    python3-dev \
    pkg-config \
    gnupg \
    postgresql-common \
    ca-certificates && \
    echo | /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh && \
    apt-get install --yes postgresql-client-15 && \
    rm -rf /var/lib/apt/lists/*

# فقط کپی و اجرایی کردن gosu بدون gpg
COPY gosu-amd64 /usr/local/bin/gosu
RUN chmod +x /usr/local/bin/gosu

RUN apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false

RUN pip install --upgrade pip "gunicorn==20.0.4"

# ایجاد دایرکتوری پروژه و تنظیم مالکیت
RUN mkdir -p /home/backend && chown sufob:sufob /home/backend
WORKDIR /home/backend

# فقط requirements رو کپی کن و نصب کن (فایل کوچیک با تغییرات کم)
COPY --chown=sufob:sufob requirements.txt .
RUN pip install -r requirements.txt

# حالا فایل‌های بزرگ سورس پروژه رو کپی کن (احتمال تغییر زیاد)
COPY --chown=sufob:sufob . .

# کپی و اجازه اجرای entrypoint
COPY ./entrypoint.backend.dev.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.backend.dev.sh

ENTRYPOINT ["entrypoint.backend.dev.sh"]
