# Generated by Django 4.2.11 on 2025-08-08 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrollTimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_shamsi', models.CharField(max_length=10, verbose_name='تاریخ شروع (شمسی)')),
                ('end_date_shamsi', models.CharField(max_length=10, verbose_name='تاریخ پایان (شمسی)')),
                ('start_date_gregorian', models.DateField(verbose_name='تاریخ شروع (میلادی)')),
                ('end_date_gregorian', models.DateField(verbose_name='تاریخ پایان (میلادی)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('total_records', models.PositiveIntegerField(default=0, verbose_name='تعداد کل رکوردها')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='ایجاد شده توسط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_requests', to='price_models.category', verbose_name='دسته')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_requests', to='price_models.category', verbose_name='دسته اصلی')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_requests', to='price_models.category', verbose_name='زیردسته')),
            ],
            options={
                'verbose_name': 'درخواست Scroll Time',
                'verbose_name_plural': 'درخواست\u200cهای Scroll Time',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='price_data__status_33746f_idx'), models.Index(fields=['main_category', 'category'], name='price_data__main_ca_469264_idx')],
            },
        ),
    ]
