# Generated by Django 4.2.11 on 2025-08-08 21:13

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields
import wagtail_headless_preview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='مقدمه صفحه قیمت\u200cها')),
            ],
            options={
                'verbose_name': 'صفحه قیمت\u200cها',
                'verbose_name_plural': 'صفحات قیمت\u200cها',
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='PricePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('commodity_name', models.CharField(choices=[('کنسانتره آهن', 'کنسانتره آهن'), ('سنگ آهن', 'سنگ آهن'), ('کاتد مس', 'کاتد مس'), ('شمش آلومینیوم', 'شمش آلومینیوم'), ('کک متالورژی', 'کک متالورژی')], help_text='نام کالا را انتخاب کنید', max_length=100)),
                ('chart_description', wagtail.fields.RichTextField(blank=True, help_text='توضیحات چارت')),
                ('show_statistics', models.BooleanField(default=True, help_text='نمایش آمار')),
                ('chart_days', models.IntegerField(default=30, help_text='تعداد روزهای نمایش در چارت')),
            ],
            options={
                'verbose_name': 'صفحه قیمت',
                'verbose_name_plural': 'صفحات قیمت',
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'wagtailcore.page'),
        ),
    ]
