# Generated by Django 4.2.11 on 2025-08-09 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_scrolltimepage_auto_save_to_database'),
        ('price_data_ingestion', '0002_category_scrolltimerequest_auto_save_and_more'),
        ('price_display', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricepage',
            name='commodity_name',
        ),
        migrations.RemoveField(
            model_name='pricepage',
            name='show_statistics',
        ),
        migrations.AddField(
            model_name='pricepage',
            name='blog_category',
            field=models.ForeignKey(help_text='دسته\u200cبندی وبلاگ برای نمایش ۳ پست آخر', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory', verbose_name='فهرست مطالب'),
        ),
        migrations.AddField(
            model_name='pricepage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_pages', to='price_data_ingestion.category', verbose_name='گروه'),
        ),
        migrations.AddField(
            model_name='pricepage',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_pages', to='price_data_ingestion.maincategory', verbose_name='گروه اصلی'),
        ),
        migrations.AddField(
            model_name='pricepage',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_pages', to='price_data_ingestion.subcategory', verbose_name='زیرگروه'),
        ),
    ]
