# Generated by Django 4.2.11 on 2025-08-05 22:45

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('blog', '0006_blogcategory_description_blogcategory_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrollTimePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='توضیحات')),
                ('api_url', models.URLField(blank=True, help_text='آدرس API برای دریافت داده\u200cهای بورس', verbose_name='آدرس API')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
