# Generated by Django 4.2.11 on 2025-08-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_scrolltimepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrolltimepage',
            name='auto_fetch',
            field=models.BooleanField(default=False, verbose_name='دریافت خودکار'),
        ),
        migrations.AddField(
            model_name='scrolltimepage',
            name='cat',
            field=models.IntegerField(default=49, verbose_name='دسته فرعی'),
        ),
        migrations.AddField(
            model_name='scrolltimepage',
            name='from_date',
            field=models.CharField(default='1404/04/01', help_text='مثال: 1404/04/01', max_length=10, verbose_name='تاریخ شروع (شمسی)'),
        ),
        migrations.AddField(
            model_name='scrolltimepage',
            name='last_fetch_count',
            field=models.IntegerField(default=0, verbose_name='تعداد رکورد آخرین دریافت'),
        ),
        migrations.AddField(
            model_name='scrolltimepage',
            name='last_fetch_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین دریافت'),
        ),
        migrations.AddField(
            model_name='scrolltimepage',
            name='main_cat',
            field=models.IntegerField(default=1, verbose_name='دسته اصلی'),
        ),
        migrations.AddField(
            model_name='scrolltimepage',
            name='producer',
            field=models.IntegerField(default=0, verbose_name='تولیدکننده'),
        ),
        migrations.AddField(
            model_name='scrolltimepage',
            name='sub_cat',
            field=models.IntegerField(default=477, verbose_name='زیردسته'),
        ),
        migrations.AddField(
            model_name='scrolltimepage',
            name='to_date',
            field=models.CharField(default='1404/04/29', help_text='مثال: 1404/04/29', max_length=10, verbose_name='تاریخ پایان (شمسی)'),
        ),
        migrations.AlterField(
            model_name='scrolltimepage',
            name='api_url',
            field=models.URLField(default='https://www.ime.co.ir/subsystems/ime/services/home/imedata.asmx/GetAmareMoamelatList', help_text='آدرس API برای دریافت داده\u200cهای بورس', verbose_name='آدرس API'),
        ),
    ]
