# Generated by Django 4.2.11 on 2025-08-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_scrolltimepage_auto_fetch_scrolltimepage_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrolltimepage',
            name='auto_save_to_database',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، هنگام ذخیره صفحه، داده\u200cها از API دریافت و در پایگاه داده ذخیره خواهد شد', verbose_name='ذخیره خودکار در پایگاه داده'),
        ),
    ]
