# Generated by Django 4.2.11 on 2025-08-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=20, verbose_name='کد ISIN')),
                ('symbol', models.CharField(max_length=50, verbose_name='نماد')),
                ('company_name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('trade_date', models.DateField(verbose_name='تاریخ معامله')),
                ('trade_date_shamsi', models.CharField(max_length=10, verbose_name='تاریخ شمسی')),
                ('weighted_final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت پایانی موزون')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت پایانی')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='پایین\u200cترین قیمت')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='بالاترین قیمت')),
                ('first_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت اولین معامله')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت پایه عرضه')),
                ('contracts_volume', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='حجم قراردادها')),
                ('supply_volume', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='حجم عرضه')),
                ('demand_volume', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='حجم تقاضا')),
                ('trade_value', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='ارزش معاملات (هزار ریال)')),
                ('trades_count', models.IntegerField(default=0, verbose_name='تعداد معاملات')),
                ('buyer_seller_power_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='نسبت قدرت خریدار به فروشنده')),
                ('source', models.CharField(default='scroll-time', max_length=100, verbose_name='منبع داده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تمام داده\u200cها',
                'verbose_name_plural': 'تمام داده\u200cها',
                'db_table': 'data_management_all_data',
                'ordering': ['-trade_date', 'symbol'],
                'unique_together': {('isin', 'trade_date')},
            },
        ),
    ]
