# Generated by Django 4.2.11 on 2025-08-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_alldata'),
    ]

    operations = [
    ]
