# Generated by Django 4.2.11 on 2025-08-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_auto_20250805_2333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyData',
        ),
        migrations.DeleteModel(
            name='DataAggregationLog',
        ),
        migrations.DeleteModel(
            name='MonthlyData',
        ),
        migrations.DeleteModel(
            name='WeeklyData',
        ),
        migrations.DeleteModel(
            name='YearlyData',
        ),
        migrations.AlterModelOptions(
            name='alldata',
            options={'ordering': ['-transaction_date', 'symbol'], 'verbose_name': 'تمام داده\u200cها', 'verbose_name_plural': 'تمام داده\u200cها'},
        ),
        migrations.AlterUniqueTogether(
            name='alldata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alldata',
            name='api_endpoint',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نقطه انتهایی API'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='arzeh_pk',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه عرضه'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='b_arzeh_radif_tar_sarresid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='broker',
            field=models.CharField(blank=True, max_length=100, verbose_name='کارگزار'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='commodity_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام کالا'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='contract_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='نوع قرارداد'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='contract_volume',
            field=models.IntegerField(default=0, verbose_name='حجم قرارداد'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ارز'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='hall',
            field=models.CharField(blank=True, max_length=100, verbose_name='تالار'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='highest_price',
            field=models.FloatField(blank=True, null=True, verbose_name='بیشترین قیمت'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='lowest_price',
            field=models.FloatField(blank=True, null=True, verbose_name='کمترین قیمت'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='method_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شرح نحوه'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='mode_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شرح روش'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='offer_volume',
            field=models.IntegerField(default=0, verbose_name='حجم عرضه'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='packet_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام بسته'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='producer',
            field=models.CharField(blank=True, max_length=200, verbose_name='تولیدکننده'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='raw_data',
            field=models.JSONField(blank=True, null=True, verbose_name='داده خام'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='settlement_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تسویه'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='settlement_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='نحوه تسویه'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, verbose_name='عرضه\u200cکننده'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=10, verbose_name='تاریخ معامله شمسی'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='transaction_value',
            field=models.BigIntegerField(default=0, verbose_name='ارزش معامله'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='واحد'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='warehouse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='انبار'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='x_talar_report_pk',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه گزارش تالار'),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='base_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت پایه'),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='demand_volume',
            field=models.IntegerField(default=0, verbose_name='حجم تقاضا'),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='final_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت نهایی'),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, verbose_name='نماد'),
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='buyer_seller_power_ratio',
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='contracts_volume',
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='first_price',
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='isin',
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='supply_volume',
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='trade_date',
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='trade_date_shamsi',
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='trade_value',
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='trades_count',
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='weighted_final_price',
        ),
    ]
