# Generated by Django 4.2.11 on 2025-08-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0004_delete_dailydata_delete_dataaggregationlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='contract_volume',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='حجم قرارداد'),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='transaction_value',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='ارزش معامله'),
        ),
    ]
