# Generated by Django 4.2.11 on 2025-08-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0005_alter_alldata_contract_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت پایه'),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت نهایی'),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='highest_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='بیشترین قیمت'),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='lowest_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='کمترین قیمت'),
        ),
        migrations.AddIndex(
            model_name='alldata',
            index=models.Index(fields=['commodity_name', 'transaction_date'], name='data_manage_commodi_96b592_idx'),
        ),
        migrations.AddIndex(
            model_name='alldata',
            index=models.Index(fields=['symbol', 'transaction_date'], name='data_manage_symbol_58f890_idx'),
        ),
        migrations.AddIndex(
            model_name='alldata',
            index=models.Index(fields=['source', 'created_at'], name='data_manage_source_da6828_idx'),
        ),
        migrations.AddIndex(
            model_name='alldata',
            index=models.Index(fields=['producer'], name='data_manage_produce_fb9569_idx'),
        ),
        migrations.AddIndex(
            model_name='alldata',
            index=models.Index(fields=['transaction_date'], name='data_manage_transac_463b89_idx'),
        ),
    ]
