# Generated by Django 4.2.11 on 2025-08-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_dailydata_dataaggregationlog_yearlydata_weeklydata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityYearlyPriceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('year', models.IntegerField(verbose_name='سال شمسی')),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='میانگین قیمت نهایی')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='کمترین قیمت')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='بیشترین قیمت')),
                ('total_volume', models.BigIntegerField(default=0, verbose_name='مجموع حجم معاملات')),
                ('transaction_count', models.IntegerField(default=0, verbose_name='تعداد معاملات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سری قیمت سالانه کالا',
                'verbose_name_plural': 'سری\u200cهای قیمت سالانه کالاها',
                'db_table': 'commodity_yearly_price_series',
                'ordering': ['-year', 'commodity_name'],
                'unique_together': {('commodity_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CommodityWeeklyPriceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('year', models.IntegerField(verbose_name='سال')),
                ('week_number', models.IntegerField(verbose_name='شماره هفته')),
                ('week_start_date', models.DateField(verbose_name='تاریخ شروع هفته')),
                ('week_end_date', models.DateField(verbose_name='تاریخ پایان هفته')),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='میانگین قیمت نهایی')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='کمترین قیمت')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='بیشترین قیمت')),
                ('total_volume', models.BigIntegerField(default=0, verbose_name='مجموع حجم معاملات')),
                ('transaction_count', models.IntegerField(default=0, verbose_name='تعداد معاملات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سری قیمت هفتگی کالا',
                'verbose_name_plural': 'سری\u200cهای قیمت هفتگی کالاها',
                'db_table': 'commodity_weekly_price_series',
                'ordering': ['-year', '-week_number', 'commodity_name'],
                'unique_together': {('commodity_name', 'year', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='CommodityMonthlyPriceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('year', models.IntegerField(verbose_name='سال')),
                ('month', models.IntegerField(verbose_name='ماه')),
                ('month_shamsi', models.CharField(max_length=7, verbose_name='ماه و سال شمسی')),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='میانگین قیمت نهایی')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='کمترین قیمت')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='بیشترین قیمت')),
                ('total_volume', models.BigIntegerField(default=0, verbose_name='مجموع حجم معاملات')),
                ('transaction_count', models.IntegerField(default=0, verbose_name='تعداد معاملات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سری قیمت ماهانه کالا',
                'verbose_name_plural': 'سری\u200cهای قیمت ماهانه کالاها',
                'db_table': 'commodity_monthly_price_series',
                'ordering': ['-year', '-month', 'commodity_name'],
                'unique_together': {('commodity_name', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CommodityDailyPriceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('trade_date', models.DateField(verbose_name='تاریخ معامله')),
                ('trade_date_shamsi', models.CharField(max_length=10, verbose_name='تاریخ شمسی')),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='میانگین قیمت نهایی')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='کمترین قیمت')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='بیشترین قیمت')),
                ('total_volume', models.BigIntegerField(default=0, verbose_name='مجموع حجم معاملات')),
                ('transaction_count', models.IntegerField(default=0, verbose_name='تعداد معاملات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سری قیمت روزانه کالا',
                'verbose_name_plural': 'سری\u200cهای قیمت روزانه کالاها',
                'db_table': 'commodity_daily_price_series',
                'ordering': ['-trade_date', 'commodity_name'],
                'indexes': [models.Index(fields=['commodity_name', 'trade_date'], name='commodity_d_commodi_4d999a_idx'), models.Index(fields=['trade_date'], name='commodity_d_trade_d_d0ea19_idx')],
                'unique_together': {('commodity_name', 'trade_date')},
            },
        ),
    ]
