# Generated by Django 4.2.11 on 2025-08-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0008_commodityyearlypriceseries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAggregationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation_type', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('yearly', 'سالانه'), ('all', 'همه موارد')], max_length=20, verbose_name='نوع تجمیع')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('records_processed', models.IntegerField(default=0, verbose_name='تعداد رکوردهای پردازش شده')),
                ('records_created', models.IntegerField(default=0, verbose_name='تعداد رکوردهای ایجاد شده')),
                ('records_updated', models.IntegerField(default=0, verbose_name='تعداد رکوردهای بروزرسانی شده')),
                ('success', models.BooleanField(default=False, verbose_name='موفقیت‌آمیز')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
            ],
            options={
                'verbose_name': 'لاگ تجمیع داده',
                'verbose_name_plural': 'لاگ‌های تجمیع داده',
                'db_table': 'data_management_aggregation_log',
                'ordering': ['-start_time'],
            },
        ),
    ]
