# Generated by Django 5.2.4 on 2025-07-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_importlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('hall', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=200)),
                ('contract_type', models.CharField(max_length=50)),
                ('final_price', models.FloatField(blank=True, null=True)),
                ('transaction_value', models.BigIntegerField(default=0)),
                ('lowest_price', models.FloatField(blank=True, null=True)),
                ('highest_price', models.FloatField(blank=True, null=True)),
                ('base_price', models.FloatField()),
                ('offer_volume', models.IntegerField()),
                ('demand_volume', models.IntegerField()),
                ('contract_volume', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('transaction_date', models.CharField(max_length=10)),
                ('supplier', models.CharField(max_length=200)),
                ('broker', models.CharField(max_length=100)),
                ('settlement_type', models.CharField(max_length=50)),
                ('delivery_date', models.CharField(blank=True, max_length=10, null=True)),
                ('warehouse', models.CharField(blank=True, max_length=100, null=True)),
                ('settlement_date', models.CharField(blank=True, max_length=10, null=True)),
                ('x_talar_report_pk', models.IntegerField(blank=True, null=True, unique=True)),
                ('b_arzeh_radif_tar_sarresid', models.CharField(blank=True, max_length=10, null=True)),
                ('mode_description', models.CharField(blank=True, max_length=50, null=True)),
                ('method_description', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('packet_name', models.CharField(blank=True, max_length=50, null=True)),
                ('arzeh_pk', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
