# Generated by Django 5.2.4 on 2025-07-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_stagedtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_final_price', models.CharField(max_length=20)),
                ('final_price', models.CharField(max_length=20)),
                ('lowest_price', models.CharField(max_length=20)),
                ('highest_price', models.CharField(max_length=20)),
                ('weekly_range', models.CharField(max_length=30)),
                ('monthly_range', models.CharField(max_length=30)),
                ('monthly_change', models.CharField(max_length=20)),
                ('settlement_type', models.CharField(max_length=20)),
                ('transaction_date', models.CharField(max_length=10)),
                ('contract_volume', models.CharField(max_length=20)),
                ('demand', models.CharField(max_length=20)),
                ('offer_volume', models.CharField(max_length=20)),
                ('base_price', models.CharField(max_length=20)),
                ('transaction_value', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
