# Generated by Django 4.2.11 on 2025-08-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
